### ISSUE TITLE
DocumentPuzzles.java:45-48: Add better validation of the...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-todos#10]
The puzzle `6-c0142e95` from #6 has to be resolved: 

https://github.com/self-xdsd/self-todos/blob/d7b687e1f2f72c1c13d2a06f06f940554aa71116/src/main/java/com/selfxdsd/todos/DocumentPuzzles.java#L45-L48

The puzzle was created by @amihaiemil on 07-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil I'll work on this.
I think validating against this schema http://pdd-xsd.teamed.io/0.19.4.xsd should be enough.

**Comment by amihaiemil** [comment]
@criske I think a simple ``if(input startsWith "<?xml version="1.0"?>")`` would be enough.

If the ``puzzles.xml`` file starts with that line, then we know it's a valid XML and we can safely assume it's the ``<puzzles>`` XML we are expecting.

If the input String does not start with that line, then add it as a message to the exception. 
Later, if a processing exception is thrown, we should leave a comment in the Commit which triggered the whole process. But we'll do that in another Issue.

**Comment by criske** [comment]
@amihaiemil is really easy to implement, there is already a validator for xml in jdk :D. So max 5-6 lines of code and `xsd` in resources and we're good to go.

**Comment by amihaiemil** [comment]
paid with transaction id 83F50033H5527703U

**Comment by 0pdd** [comment]
The puzzle `6-c0142e95` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
