### ISSUE TITLE
SshPuzzles.java: Write unit test for SshPuzzle... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-todos#39]
The puzzle ``7-31ff0f72`` originating from #7 has to be resolved:

https://github.com/self-xdsd/self-todos/blob/09c70978a11fac263f458ebe74320b2fe62ed2e7/src/main/java/com/selfxdsd/todos/SshPuzzles.java#L46-L47

"Write unit test for SshPuzzles and unit DocumentPuzzles for cases when there are invalid documents.".

It was created by cristianpela on 2020-09-02T14:27:15Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-06T18:48:07.405353``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@fellahi-ali forget about DocumentPuzzles, it has been renamed to XmlPuzzles and is not being used at the moment.

**Comment by charlesmike** [comment]
@fellahi-ali Don't forget to close this ticket before the deadline (2021-01-06T18:48:07). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
paid with transaction id 91X86750M57886423

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@fellahi-ali thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
