### ISSUE TITLE
SshPuzzles.java:41-42: Transform the puzzles XML string...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-todos#5]
The puzzle `3-fec5f6c3` from #3 has to be resolved: 

https://github.com/self-xdsd/self-todos/blob/eda8071931cd115c96f415bb035750f0c472d510/src/main/java/com/selfxdsd/todos/SshPuzzles.java#L41-L42

The puzzle was created by @amihaiemil on 01-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
@criske Arunca un ochi peste proiectu asta cand ai timp/chef :D 

Va fi un microserviciu mic, cu un endpoint, care se va conecta prin SSH la un server (initial localhost, cel mai probabil), unde va clona Project-ul, va rula utilitara [pdd](https://github.com/yegor256/pdd) si va deschide/inchide ticketele in functie de todo-uri.

In principiu e un inlocuitor pt ``0pdd``, ca sa nu-i punem pe useri sa foloseasca tool-uri third party, ca nu e dragut :D

**Comment by criske** [comment]
@amihaiemil E foarte misto conceptul :D.
O mica nelamurire am. Nu e cam overkill jaxb pentru treaba asta? Eu zic ca xml dom e arhisuficent pentru cat de simpla e schema `puzzles.xml`.

Pot sa ma ocup de puzzle-ul asta, daca-i ok :)
Ma gandesc ca o sa fie cam acelasi pattern folosit in alte parti.
Un iterable `Puzzles` pentru `Puzzle` care va avea `Puzzles::ofProject(Project)`.
Probabil ca actualul controller `Puzzles` se va redenumi atunci `PuzzlesApi` sau ceva de genu?

**Comment by amihaiemil** [comment]
@criske si DOM api e ok, daca se poate. Am mucrat ft putin cu XML, nu stiu cum e cel mai simplu :D 

Poate fi Puzzles Iterable de Puzzle, dar nube nevoie de ofProject pt ca va fi un singur Project per Request, toate puzzle-urile citite vor fi ale lui.

**Comment by amihaiemil** [comment]
@criske stii sa-ti faci o cheie SSH de test, sa te poti conecta la localhost?  Daca nu, scriu maine un fisier aici, cum trebuie facut.

**Comment by criske** [comment]
@amihaiemil cu `ssh-keygen` nu? dar poti sa lasi un ghid :)

**Comment by amihaiemil** [comment]
@criske da, ceva pe-acolo, cu ssh keygen :D

**Comment by amihaiemil** [comment]
@criske cam asa se face cu cheile alea https://github.com/self-xdsd/self-todos/blob/master/ssh_localhost_howto.md :)

**Comment by criske** [comment]
@amihaiemil mersi

**Comment by criske** [comment]
@amihaiemil tie iti merge clonatul `self-xdsd/self-web` prin ssh?
Imi da:
```
Cloning into 'self-web'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
Am incercat si prin putty (sunt pe win) si la fel.

Daca-l clonez pe server manual imi merge fara probleme.

**Comment by criske** [comment]
@amihaiemil Ok, dupa ceva stackoverflowing am rezolvat pe partea mea, trebuia adaugat key-ul la agent, chiar daca pe server este adaugat:
``` java
ssh.exec("rm -r self-todos-temp/*");
shh.exec("eval `ssh-agent -s`; ssh-add ~/.ssh/id_rsa_self && cd self-todos-temp &&"
             + "git clone git@github.com:self-xdsd/self-web.git && "
             + "cd self-web && "
             + "pdd . > puzzles.xml");
ssh.exec( "cd self-todos-temp/self-web && cat ./puzzles.xml");
```

**Comment by amihaiemil** [comment]
@criske da da, trebuie curatat.
Nu stiu de ce da permission denied, sincer, mie imi merge bine. Poate pt ca sunt admin pe organizatie?

Oricum, comanda aia de clone va fi putin diferita, va trebui sa-i specificam token-u de acces al PM-ului, cel mai probabil :D

**Comment by criske** [comment]
> @criske da da, trebuie curatat.
> Nu stiu de ce da permission denied, sincer, mie imi merge bine. Poate pt ca sunt admin pe organizatie?

Nu cred, imi dadea denied si pentru `ssh -T git@github.com`, cred ca tine de os. O sa incerc rulez aplicatia spring prin docker sa nu mai fie probleme de compatibilitate.

> Oricum, comanda aia de clone va fi putin diferita, va trebui sa-i specificam token-u de acces al PM-ului, cel mai probabil :D

Cred ca o sa fie nevoie si de username.
Atunci ma gandesc ca ssh serverul nu o sa mai aiba nevoie de pub key inregistrat pe github.

**Comment by amihaiemil** [comment]
@criske  

>  Atunci ma gandesc ca ssh serverul nu o sa mai aiba nevoie de pub key inregistrat pe github.

Ba da, cred ca tot va trebui. Dar asta nu-i asa important oricum :D

**Comment by criske** [comment]
@amihaiemil 
Am incercat cu `git clone https://criske:<token>@github.com/self-xdsd/self-web.git` si a mers fara ca serverul sa aiba drepturi pe github.

**Comment by amihaiemil** [comment]
@criske da, prin HTTPS e alta treaba. E ok ca merge asa, mersi de info 👍

**Comment by 0pdd** [comment]
The puzzle `3-fec5f6c3` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
