### ISSUE TITLE
Drop Async Puzzle Review

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-todos#65]
Due to #63

**Comment by zoeself** [comment]
@amihaiemil thank you for reporting this. Unfortunately, @amihaiemil is not a contributor with the required role (DEV), that's why I unassigned them. 

I will assign a contributor to take care of it soon.

**Comment by amihaiemil** [comment]
@criske Scoti Async in task-u asta pls? Doar atat, nu trebuie schimbari pt fancy tests sau stiu eu :D

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-06-01T08:16:42.402467``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
