### ISSUE TITLE
Getting Commits Is Unauthenticated

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-todos#69]
The Repo used for getting the commits is unauthenticated so this call fails with 404 for private repos. let's fix it.

**Comment by zoeself** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-09-12T22:00:36.389057``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by criske** [comment]
Isn't already authenticated with pm's token in core's  `[Gh/Gl]WebhookEvent`?
https://github.com/self-xdsd/self-core/blob/ac4f1e28d64d6640aa046919a18ebc526eae60bb/self-core-impl/src/main/java/com/selfxdsd/core/projects/GithubWebhookEvent.java#L121-L137
``` java
this.project.projectManager().provider()
```
Where pm provider is from `StoredProjectManager`
https://github.com/self-xdsd/self-core/blob/ac4f1e28d64d6640aa046919a18ebc526eae60bb/self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java#L191-L200

**Comment by amihaiemil** [comment]
@criske that's the commit which triggered the Push and yes, it's authenticated. But the problem is in JsonPuzzles, when getting the latest commit from the repo: https://github.com/self-xdsd/self-todos/blob/master/src/main/java/com/selfxdsd/todos/JsonPuzzles.java#L85

That Repo (``this.project.repo()``) is not authenticated : D

**Comment by amihaiemil** [comment]
@criske A bit of context: we first use the Event.commit() to get the Commit which triggered the push (to comment on it about open/closed tickets) and we also need the latest commit from the Repo (which might be a different one), in order to referentiate the TODO in the Issue Description.

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
